#include "Descriptors.h"

#if (USE_INTERNAL_SERIAL == NO_DESCRIPTOR)
	#warning USE_INTERNAL_SERIAL is not available on this AVR - please manually construct a device serial descriptor.
#endif

#ifdef USB_MOUSE
MOUSE_REPORT_DEFAULT
#endif
#ifdef USB_JOY
JOYSTICK_REPORT_DEFAULT
#endif

DEVICE_DESC(USB_CSCP_IADDeviceClass, USB_CSCP_IADDeviceSubclass, USB_CSCP_IADDeviceProtocol, 0x03EB, 0x2062, 0.01)

CONFIG_DESC_BEGIN(3,1,100)
#ifdef USB_CDC
CDC_CONFIG_DEFAULT,
#endif
#ifdef USB_MOUSE
MOUSE_CONFIG_DESC
#endif
#ifdef USB_JOY
HID_JS_CONFIG_DEFAULT
#endif
CONFIG_DESC_END

LANG_DEFAULT
MANUFACTURER(L"Avrthing",8)
PRODUCT(L"Virtual Serial and Mouse Demo",29)
//PRODUCT(L"Virtual Serial and JS Demo",26)

GETDESCRIPTOR_CALLBACK_BEGIN
#ifdef USB_MOUSE
GETDESCRIPTOR_CALLBACK_MOUSE
#endif
#ifdef USB_JOY
GETDESCRIPTOR_CALLBACK_HID_JS
#endif
GETDESCRIPTOR_CALLBACK_END

