#include "Descriptors.h"

JOYSTICK_REPORT(2, -100, 100, -1, 1, 2);

DEVICE_DESC_DEFAULT;

CONFIG_DESC_BEGIN(3,1,100)
HID_JS_CONFIG_DEFAULT,
CDC_CONFIG_DEFAULT,
CONFIG_DESC_END;

LANG_DEFAULT
MANUFACTURER(L"Avrthing",8)
PRODUCT(L"Joystick Demo",13)

GETDESCRIPTOR_CALLBACK_BEGIN
GETDESCRIPTOR_CALLBACK_HID
GETDESCRIPTOR_CALLBACK_END



#if (USE_INTERNAL_SERIAL == NO_DESCRIPTOR)
	#warning USE_INTERNAL_SERIAL is not available on this AVR - please manually construct a device serial descriptor.
#endif

