#include "Descriptors.h"

JOYSTICK_REPORT(2, -100, 100, -1, 1, 2);

DEVICE_DESC_DEFAULT;

CONFIG_DESC_BEGIN(1,1,100)
HID_JS_CONFIG_DEFAULT
CONFIG_DESC_END;

LANG_DEFAULT
MANUFACTURER(L"Avrthing",8)
PRODUCT(L"Joystick Demo",13)

GETDESCRIPTOR_CALLBACK_BEGIN
GETDESCRIPTOR_CALLBACK_HID
GETDESCRIPTOR_CALLBACK_END
